name: Build and deploy to nuget.org

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build -c Release

    - name: Run tests
      run: dotnet test

    - name: Create the package
      run: dotnet pack -c Release

    - name: Publish on nuget.org
      run: dotnet nuget push "./Gravatar/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json